[BE] 유저 정보 조회 api를 만든다. #86
woowacourse-teams/2021-darass pull request #101
Opened 2021-07-14 11:33 UTC by jujubebat

- 유저 조회, 유저 닉네임 수정, 유저 삭제 api 구현완료
- rest docs 작성 완료 
- 인수 테스트, 서비스 통합 테스트 구현 완료 
#### 발생했던 이슈 
- jackson 라이브러리를 사용하여, `LocalDateTime` 필드를 가지고 있는 DTO변환시 오류가 발생했음
- jackson-datatype-jsr310 의존성을 추가하고, DTO의 `LocalDateTime` 필드에 애노테이션을 붙여줘서 해결 
- 다음링크를 참고함 https://m.blog.naver.com/writer0713/221615276956

2021-07-14 13:30 UTC, jaeseongDev requested changes

2021-07-14 13:30 UTC, jaeseongDev commented on backend/src/main/java/com/darass/darass/user/domain/User.java
> +
혹시 이 부분을 추가한 이유가 있을까요 ? ?

2021-07-14 13:48 UTC, Sehwan-Jang approved these changes
너무 수고하셨어용~

2021-07-14 13:48 UTC, Sehwan-Jang commented on backend/src/main/java/com/darass/darass/comment/controller/dto/UserResponse.java
> +    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
오 `@JsonDeserialize` 를 사용하면 매핑이 가능하게 되는 건가요??
하나 배워갑니다~ 👍

2021-07-14 13:48 UTC, Sehwan-Jang commented on backend/src/main/java/com/darass/darass/user/service/UserService.java
> +        return UserResponse.of(user, user.getUserType());
디미터의 법칙을 적용해 한줄 띄어주는 것을 어떨까요?🙏

2021-07-14 13:48 UTC, Sehwan-Jang commented on backend/src/test/java/com/darass/darass/user/controller/UserAcceptanceTest.java
> +    @DisplayName("유저 조회를 실패한다.")
경우에 따라서 실패하는 경우가 여러가지가 될 수 있을 것 같은데요 (지금은 아니더라도)
개인적인 의견이지만
어떤 이유로 조회에 실패하게 되는 건지도 명시 한다면 더 직관 적으로 보일 수 있을 것 같아요~

2021-07-14 14:45 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/user/domain/User.java
> +
유저 삭제 api를 구현하던중 유저 엔티티가 삭제되지 않는 이슈가 발생했습니다!
왜 그런지 로그를 보니, 코멘트 엔티티가 외래키로 참조하고 있었기 때문이었어요.
그래서 양방향 매핑을 통해 유저가 지워질 경우 코멘트도 같이 지워지도록 했습니다~ 

하지만 지금 생각해보니, 유저를 삭제할때 유저가 이전에 작성했던 댓글까지 모두 삭제하는게 맞는지에 대한 고민이 떠오르네요 제리는 어떻게 생각하시나요??

2021-07-14 14:51 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/user/service/UserService.java
> +        return UserResponse.of(user, user.getUserType());
반영 했습니다. 👍👍👍

2021-07-14 14:51 UTC, jujubebat commented on backend/src/test/java/com/darass/darass/user/controller/UserAcceptanceTest.java
> +    @DisplayName("유저 조회를 실패한다.")
좋은 생각 입니다~ 반영 완료했습니다!!!!

2021-07-14 18:33 UTC, jaeseongDev commented on backend/src/main/java/com/darass/darass/user/domain/User.java
> +
> 유저 삭제 api를 구현하던중 유저 엔티티가 삭제되지 않는 이슈가 발생했습니다!
왜 그런지 로그를 보니, 코멘트 엔티티가 외래키로 참조하고 있었기 때문이었어요.
그래서 양방향 매핑을 하고, 카스케이드, 고아 객체 설정을 통해 유저가 지워질 경우 코멘트도 같이 지워지도록 했습니다~

프로덕션 코드에서 `List<Comment> comments`를 활용한 코드는 있지 않아서 질문 드렸어요!
이건 궁금해서 질문드리는건데, `List<Comment> comments`를 선언하지 않으면 CASCADE처럼 사용할 수가 없는 거겠죠... ?

> 유저를 삭제할때 유저가 이전에 작성했던 댓글까지 모두 삭제하는게 맞는지에 대한 고민이 떠오르네요.
제리는 어떻게 생각하시나요??

유저를 삭제할 때 댓글을 모두 삭제한다고 해서 지금 현재로서는 크게 문제가 되지 않을 것 같네요! 지금 코드 그대로 유지해도 괜찮을 것 같습니다:)

2021-07-15 00:45 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/user/domain/User.java
> +
> 프로덕션 코드에서 List<Comment> comments를 활용한 코드는 있지 않아서 질문 드렸어요!
이건 궁금해서 질문드리는건데, List<Comment> comments를 선언하지 않으면 CASCADE처럼 사용할 수가 없는 거겠죠... ?

저도 이부분에 대해 조금 찜찜 했는데요, 지금 가진 jpa 지식으론 다른 방법이 떠오르지 않네요. 일단 이렇게 두고 더 좋은 방법이 생각나면 리팩토링 해볼게요!!

2021-07-15 00:56 UTC, jaeseongDev commented
충돌만 해결하시고 바로 셀프 squash and merge 하시면 될 것 같습니다!

2021-07-15 02:07 UTC, merged