[BE] 로깅 기능 달기
woowacourse-teams/2021-darass pull request #127
Opened 2021-07-16 11:07 UTC by Sehwan-Jang

+ 에러, 엑세스 로그 설정
+ 콘솔, 파일 로그 설정

2021-07-16 12:32 UTC, jujubebat reviewed
로깅 설정 감사합니다!! 변경 내역 확인하면서 로깅에 대해 공부해볼 수 있었어요 ㅎㅎㅎ 간단한 피드백도 달았습니다!!

2021-07-16 12:32 UTC, jujubebat commented on backend/src/main/resources/logback.xml
> +            <fileNamePattern>${logHome}/%d{yyyyMMdd}/%d{yyyyMMdd}.%i.subway-error.log</fileNamePattern>
파일 이름에 `subway-error` 가 있는데, 수정해줘야 할 것 같습니다!!

2021-07-16 12:32 UTC, jujubebat commented on backend/src/main/resources/logback-access.xml
> +            <maxHistory>1</maxHistory>
엑세스 로그 보관 기한은 1일이면 적당한지 궁금합니다!

2021-07-16 22:09 UTC, jaeseongDev requested changes
구현하시느라 고생 많으셨어요!
로깅 나중에 강의해주세요~~~ 아선생님!

2021-07-16 22:09 UTC, jaeseongDev commented on backend/src/main/resources/logback-access.xml
> +            <maxHistory>1</maxHistory>
저도 로그 기한을 최소한 30일 이상으로 늘리는 것은 어떨까 생각합니다!

2021-07-16 22:09 UTC, jaeseongDev commented on backend/src/main/resources/logback.xml
> +            <level>DEBUG</level>
로깅하는 레벨을 DEBUG로 잡는 것에 대해서 어떻게 생각하시나요~?

2021-07-17 03:12 UTC, Sehwan-Jang commented on backend/src/main/resources/logback.xml
> +            <fileNamePattern>${logHome}/%d{yyyyMMdd}/%d{yyyyMMdd}.%i.subway-error.log</fileNamePattern>
수정했습니다~

2021-07-17 03:13 UTC, Sehwan-Jang commented on backend/src/main/resources/logback-access.xml
> +            <maxHistory>1</maxHistory>
이부분 확인을 못했네요 
감사합니다~

2021-07-17 04:12 UTC, jaeseongDev requested changes

2021-07-17 04:12 UTC, jaeseongDev commented on backend/src/main/java/com/darass/darass/exception/controller/AdviceController.java
> +    Logger log = LoggerFactory.getLogger(this.getClass());
롬복을 쓰고 있으면 @Slf4j을 사용할 수 있는 걸로 알고 있는데, 이를 활용해서 코드를 리팩토링 해보는 게 어떨까요 ?

2021-07-17 04:27 UTC, Sehwan-Jang commented on backend/src/main/resources/logback.xml
> +            <level>DEBUG</level>
아 이부분은 해당 레벨 이한의 경우 포함하지 말라는 의미인데 
불필요한 부분인 것 같아 삭제했습니다

2021-07-17 04:28 UTC, jaeseongDev commented on backend/build.gradle
> +    implementation 'net.rakugakibox.spring.boot:logback-access-spring-boot-starter:2.7.1'
제가 정확히 잘 몰라서 그런데 spring-boot-starter-web에 logback이 아마 내장되어 있는 걸로 알고 있는데, 
이 의존성으로 별도로 추가한 이유가 있을까요~?

2021-07-20 13:22 UTC, merged