[BE] DB 날짜 데이터 kst로 출력되도록 변경하기 (#125)
woowacourse-teams/2021-darass pull request #128
Opened 2021-07-16 14:17 UTC by jujubebat

- KST와 같은 JST 기준 시간으로 설정했습니다.

2021-07-16 22:01 UTC, jaeseongDev requested changes
DB 날짜 출력되는 부분을 UST에서 KST로 수정할 때, 자바 스프링 어플리케이션에서 날짜를 수정하면 안 되는 걸로 알고 있어요! DB의 수정을 고쳐 주어야 되는 걸로 알고 있는데, 이 부분은 확실하게 테스트 해보고 다시 얘기해드릴게요:)

2021-07-17 01:50 UTC, jujubebat commented
> DB 날짜 출력되는 부분을 UST에서 KST로 수정할 때, 자바 스프링 어플리케이션에서 날짜를 수정하면 안 되는 걸로 알고 있어요! DB의 수정을 고쳐 주어야 되는 걸로 알고 있는데, 이 부분은 확실하게 테스트 해보고 다시 얘기해드릴게요:)

넵!! 근데 일단 테스트 코드로 h2 상에서는 동작하는걸로 확인했습니다!

2021-07-17 13:15 UTC, jaeseongDev approved these changes
리뷰해드린 부분 한 곳만 수정하시고 셀프 머지하셔도 될 것 같아요~!! 그리고 머지하신 다음에 프론트입장에서 날짜데이터가 정상적으로 받을 수 있는 지 프론트한테 확인 한 번만 부탁드릴게요😄

2021-07-17 13:15 UTC, jaeseongDev commented on backend/src/main/java/com/darass/darass/common/domain/BaseTimeEntity.java
> +    @LastModifiedDate()
() 괄호는 지우셔도 될 것 같애요😄😄

2021-07-17 14:22 UTC, merged