[BE] 비회원 댓글 비밀번호만 체크하는 API 만들기 / 관리자 댓글 삭제 기능 (#217)
woowacourse-teams/2021-darass pull request #230
Opened 2021-07-20 08:21 UTC by Sehwan-Jang

Close #217 

### 구현 부분
+ 댓글 비밀번호 체크하는 API 분리 
+ 관리자는 자신의 프로젝트 내의 댓글이라면 삭제할 수 있도록하는 기능 추가 
+ 해당 부분 인수테스트 및 Restdoc 작성
### 논의 할 부분
+ URL 패턴
--  현재 api url = `/api/v1/users/check-password` 
-- 이대로 괜찮은지 여러분들의 동의 필요...

2021-07-20 12:20 UTC, pjy1368 requested changes
코드는 깔끔하게 작성해 주셔서 한 가지정도 태클아닌 태클걸은 것 정도 있네요.
저는 /check-password url 괜찮다고 생각합니다.

2021-07-20 12:20 UTC, pjy1368 commented on backend/src/main/java/com/darass/darass/user/service/UserService.java
> +        Optional<User> expectedUser = users.findById(passwordCheckRequest.getGuestUserId());
```suggestion
        Optional<User> possibleUser = users.findById(passwordCheckRequest.getGuestUserId());
```
우기랑 같은 피드백을 남겼는데, Optional 변수명은 "possible + Type" 방식으로 쓰는 것이 어떨지 이야기하는 포스팅이 있었어요. 저는 더 직관적이라고 생각이 드는데 아론은 어떤가요?
https://betterprogramming.pub/useful-tips-for-naming-your-variables-8139cc8d44b5

2021-07-20 13:25 UTC, jaeseongDev approved these changes

2021-07-20 13:25 UTC, jaeseongDev commented on backend/src/main/java/com/darass/darass/user/controller/UserController.java
> +    public ResponseEntity<PasswordCheckResponse> checkGuestUserPassword(@ModelAttribute PasswordCheckRequest passwordCheckRequest) {
Get요청일 때 @RequestParam이랑 @PathParam만 사용해봐서 그런데, @ModelAttribute의 역할이 어떻게 되나요~?

2021-07-20 14:05 UTC, Sehwan-Jang commented on backend/src/main/java/com/darass/darass/user/controller/UserController.java
> +    public ResponseEntity<PasswordCheckResponse> checkGuestUserPassword(@ModelAttribute PasswordCheckRequest passwordCheckRequest) {
modelattribute를 사용하면 여러 쿼리파람들이 들어올때 그것을 하나의 dto 객체로 바인딩하여 받을 수 있습니다~
또 이 어노테이션은 생략 가능한데 가독성과 이해를 위하여 일부러 생략하지 않았습니다 ^^

2021-07-20 14:41 UTC, jujubebat reviewed
전체적으로 로직을 잘 짜주셔서 크게 피드백할 부분 찾지 못했습니다 ㅎㅎ   간단히 남긴 코맨트 참고해주세요!

2021-07-20 14:41 UTC, jujubebat commented on backend/src/docs/asciidoc/api/v1/users.adoc
> +==== Response (성공 - 비밀번호 일치하지 않는 경우)
실패가 맞지 않나요?

2021-07-20 14:41 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/user/controller/UserController.java
> +    @GetMapping("/check-password")
api  이름 괜찮다고 생각합니다! 👍 👍

2021-07-20 14:41 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/comment/service/CommentService.java
> +    private void validateIfCommentIsUpdatableByUser(User user, Comment comment) {
if와 Is를 빼고도 의미전달이 가능할 것이라고 생각하는데, 아론은 어떻게 생각하시나요?

2021-07-20 15:36 UTC, jujubebat commented on backend/src/test/java/com/darass/darass/user/controller/UserAcceptanceTest.java
> +    @DisplayName("비로그인 사용자의 비밀번호 일치여부를 조회한다.")
가독성 좋은 디스플레이 네이밍 👍👍

2021-07-20 15:36 UTC, jujubebat commented on backend/src/test/java/com/darass/darass/user/controller/UserAcceptanceTest.java
> +    }
BDD 스타일로 잘 작성해주셔서, 한 눈에 어떤 테스트인지 알아볼 수 있네요 👍

2021-07-20 15:36 UTC, jujubebat commented on backend/src/test/java/com/darass/darass/user/controller/UserAcceptanceTest.java
> +                        ))
각자 인텔리제이 포메팅 설정을 한 번 맞춰봐야 할 것 같아요.

2021-07-21 01:41 UTC, Sehwan-Jang commented on backend/src/docs/asciidoc/api/v1/users.adoc
> +==== Response (성공 - 비밀번호 일치하지 않는 경우)
비밀번호가 일치하지 않더라도 조회 자체는 실패한 것이 아니고 성공이라고 생각했었습니다😊

2021-07-21 01:42 UTC, Sehwan-Jang commented on backend/src/test/java/com/darass/darass/user/controller/UserAcceptanceTest.java
> +    }
테스트 장인이 하던대로 따라하면서 배웠습니다 ㅎㅎ

2021-07-21 01:42 UTC, Sehwan-Jang commented on backend/src/test/java/com/darass/darass/user/controller/UserAcceptanceTest.java
> +                        ))
동의합니다~

2021-07-21 01:50 UTC, Sehwan-Jang commented on backend/src/main/java/com/darass/darass/comment/service/CommentService.java
> +    private void validateIfCommentIsUpdatableByUser(User user, Comment comment) {
오호 굳이 없어도 읽힐것 같네요.
반영하겠습니다~

2021-07-21 02:10 UTC, jujubebat commented on backend/src/docs/asciidoc/api/v1/users.adoc
> +==== Response (성공 - 비밀번호 일치하지 않는 경우)
제가 꼼꼼하게 보지 못했네요 ㅠㅠ 데일리때 설명해준대로 이해했어요 😊

2021-07-21 02:50 UTC, jujubebat approved these changes
수고 많으셨습니다!!! 😊

2021-07-21 04:22 UTC, Sehwan-Jang commented on backend/src/main/java/com/darass/darass/user/service/UserService.java
> +        Optional<User> expectedUser = users.findById(passwordCheckRequest.getGuestUserId());
좋은 지적 감사합니다~ 반영했습니다!

2021-07-21 04:26 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/user/service/UserService.java
> +    public PasswordCheckResponse checkGuestUserPassword(PasswordCheckRequest passwordCheckRequest) {
해당 부분에 대해 통합 테스트 코드 작성해주셔야 할 것 같아요!

2021-07-21 04:31 UTC, pjy1368 approved these changes

2021-07-21 06:40 UTC, merged