[BE] 카카오 프사를 바꿨을 경우, 서버의 카카오 프로필 데이터가 업데이트 되지 않는 문제를 해결한다. (#202)
woowacourse-teams/2021-darass pull request #231
Opened 2021-07-20 08:33 UTC by jujubebat

# 구현 내용
- 카카오 프로필 업데이트 적용 로직구현
- 테스트용 H2 db 테이블을 삭제해주는 DatabaseCleaner 구현 
- 병렬 테스트 구현
  - 기본적으로 테스트 클래스들간은 병렬 수행, 클래스의 각 메서드들은 순차수행 하도록 설정함
  - 병렬 테스트 구현시 발생할 수 있는 동기화 문제를 어노테이션으로 해결 

close #202

2021-07-20 12:16 UTC, pjy1368 requested changes
우기 코드 리뷰해 보았어요.
전반적으로 깔끔하게 테스트 코드 잘 짜주신 것 같네요 👍
몇 가지 사소한 부분만 생각해 보시면 좋을 것 같아요.

2021-07-20 12:16 UTC, pjy1368 commented on backend/src/main/java/com/darass/darass/auth/oauth/service/OAuthService.java
> +        Optional<SocialLoginUser> expectedSocialLoginUser = socialLoginUserRepository.findByOauthId(socialLoginUser.getOauthId());
```suggestion
        Optional<SocialLoginUser> possibleSocialLoginUser = socialLoginUserRepository.findByOauthId(socialLoginUser.getOauthId());
```

Optional 네이밍을 어떻게 정할지 애매해서 나온 변수명같네요.
이와 관련하여 구글링을 좀 해봤는데, "possible + Type" 형태로 변수명을 지어보는 것은 어떨까요?
https://betterprogramming.pub/useful-tips-for-naming-your-variables-8139cc8d44b5

2021-07-20 12:16 UTC, pjy1368 commented on backend/src/test/java/com/darass/darass/DatabaseCleaner.java
> +            .filter(entityType -> entityType.getJavaType().getAnnotation(Entity.class) != null)
객체에 메시지를 보내도록 바꿔볼 수 있을까요?

2021-07-20 12:16 UTC, pjy1368 commented on backend/src/test/java/com/darass/darass/DatabaseCleaner.java
> +        }
stream을 사용하는 것은 어떨까요? 더 간결해질 것 같네요~

2021-07-20 13:31 UTC, jaeseongDev approved these changes
테스트에 대한 사랑이 느껴지는 시도이네요!
저는 Approve 목걸이 드리겠습니다:)

2021-07-20 14:01 UTC, Sehwan-Jang requested changes
정말 테스트를 엄청 깎은 흔적이 보이네요... 정말 고생하셨습니다!!!

2021-07-20 14:01 UTC, Sehwan-Jang commented on backend/src/test/resources/application.properties
> +logging.level.org.hibernate.SQL= error
서브모듈에 이미 application-test.yml이 존재하는데 굳이 여기에 따로 작성하신 이유가 있을 까요?

2021-07-20 14:54 UTC, jujubebat commented on backend/src/test/java/com/darass/darass/DatabaseCleaner.java
> +            .filter(entityType -> entityType.getJavaType().getAnnotation(Entity.class) != null)
EntityManager과 Entity는 자바에서 제공되는 클래스이기 때문에 불가능할 것 같습니다.

2021-07-20 15:03 UTC, jujubebat commented on backend/src/test/java/com/darass/darass/DatabaseCleaner.java
> +        }
```java
tableNames.forEach(tableName -> 
            entityManager.createNativeQuery("TRUNCATE TABLE " +tableName).executeUpdate());
```
이 경우 스트림을 사용할 경우 가독성이 오히려 낮아진다고 생각합니다.  또한 `Stream.forEach()`는 일반 for-loop에 비해 성능이 떨어지는 문제도 있습니다.

2021-07-20 15:04 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/auth/oauth/service/OAuthService.java
> +        Optional<SocialLoginUser> expectedSocialLoginUser = socialLoginUserRepository.findByOauthId(socialLoginUser.getOauthId());
좋은 글 감사합니다. 반영해보겠습니다~

2021-07-21 04:02 UTC, jujubebat commented on backend/src/test/java/com/darass/darass/IsolationTest.java
> +        }
맞네요 꼼꼼히 봐주셔서 감사합니다! 제거하도록 하겠습니다~~

2021-07-21 04:12 UTC, jujubebat commented on backend/src/test/resources/application.properties
> +logging.level.org.hibernate.SQL= error
application-test.yml에 위 내용을 작성해도, 로그가 계속 출력되었습니다. 위와같이 따로 빼두니까 설정대로 로그 출력이 안되더군요! 그래도 테이블 생성 sql문 로그도 계속 찍히더라구요. 아직 해결하지 못해서 일단은 이렇게 해뒀습니다.

2021-07-21 04:29 UTC, pjy1368 approved these changes

2021-07-21 04:30 UTC, Sehwan-Jang approved these changes

2021-07-21 06:43 UTC, merged