[BE] OAuth Code로 받아서 처리하도록 리팩토링 (#346)
woowacourse-teams/2021-darass pull request #417
Opened 2021-08-07 04:58 UTC by jujubebat

변경 내역에 대한 설명은 내일 정도에 작성할게요.
지금은 빌드 동작하는지 잠깐 확인용으로 PR 날립니다.

2021-08-09 08:11 UTC, jaeseongDev requested changes
리뷰 보시고 이해 안되시는 부분 있으시면,
나중에 페어프로그래밍 같이 하면서 다시 같이 고민해봐요~!!
구현하시느라 고생 많으셨어요😄😄

2021-08-09 08:11 UTC, jaeseongDev commented on backend/src/main/java/com/darass/darass/auth/oauth/api/domain/GithubOAuthProvider.java
> +    }
setter를 없애는 방향으로 코드를 수정해보면 어떨까요~?
아마 지금 현재 setter를 써야되는 형태가 상속때문에 발생한 것 같은데,
인터페이스를 활용해서 다시 코드를 수정해보는 건 어떨까요 ? ?

2021-08-09 08:11 UTC, jaeseongDev commented on backend/src/main/java/com/darass/darass/auth/oauth/api/domain/OAuthProviderFactory.java
> +        throw ExceptionWithMessageAndCode.INVALID_OAUTH_PROVIDER.getException();
다형성을 활용해서 if문을 없애도록 리팩토링 해보는 건 어떨까요~?

2021-08-09 08:11 UTC, jaeseongDev commented on backend/src/main/java/com/darass/darass/auth/oauth/service/OAuthService.java
>          }
이 부분 최근에 PR 올리고 머지된 부분에서 옵셔널 제거하고 리팩토링 했었어요~!
나중에 Rebase하시면 충돌 날 때 참고해주세요:)

2021-08-09 08:58 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/auth/oauth/api/domain/GithubOAuthProvider.java
> +    }
우선 setter 메서드의 접근 제한자를 private으로 바꿔서 설정 파일로부터 주입받는 경우 외에는 setter 메서드를 사용할 수 없도록 막아놨습니다~ 

인터페이스를 활용해서 어떤 방향으로 수정해야하는지 좀 더 설명해주실 수 있나요?

제가 상속을 사용한 이유는 위 PR 설명에 적어뒀습니다!

2021-08-09 09:06 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/auth/oauth/api/domain/OAuthProviderFactory.java
> +        throw ExceptionWithMessageAndCode.INVALID_OAUTH_PROVIDER.getException();
해당 클래스는 조건에 따라 로직이 실행되도록 하기 위함이 아니라, 조건에 따른 객체 생성을 위해서 만들었습니다.

다형성은 상속구조로 구현해뒀습니다! 현재 OAuthService 클래스의 oauthLogin 메서드 코드가 바뀌지 않으면서 oauth provider를 추가할 수 있는 구조 입니다!

provider 이름에 따른 분기문은 없앨 수 없다고 판단했었는데, 어떻게 없앨 수 있는지 알려주실 수 있나요??

2021-08-09 09:08 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/auth/oauth/service/OAuthService.java
>          }
넵 나중에 참고해서 충돌 해결하겠습니다~!

2021-08-28 05:04 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/auth/oauth/controller/OAuthController.java
> +        response.addHeader("Set-Cookie", cookie.toString());
쿠키 관련 로직은 http 요청/응답에 포함되는 것이라고 생각해서 컨트롤러로 옮겨봤습니다!

컨트롤러에서 @CookieValue라는 애너테이션을 통해 Cookie 객체를 파라미터로 받을 수 있더라구요

이 점에서 쿠키 관련 로직은 컨트롤러에 위치하는 것이 맞다고 더 느끼게 되었습니다!!

아론 생각은 어떠신가요?

2021-08-28 05:07 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/auth/oauth/api/domain/OAuthProvider.java
>          } catch (Exception e) {
감사합니다.

다만 현재 구조는 상속을 사용하는 단점이 있는데요, 제리가 저번에 컴포지션으로 바꿔보면 어떨까 제안을 줬었습니다!

고민을 조금 해봤는데, 부모 클래스에서 드러나는 oauth 요청 로직이 앞으로 변할 가능성이 크게 없다고 생각했고, 이대로 둬도 크게 문제 없지 않을까 해서 컴포지션으로 개선을 안했습니다.

하지만 제리의 의견에도 충분히 동의를 하고, 추후 컴포지션으로 바꿔도 좋을 것 같습니다 ~!

2021-08-28 05:07 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/auth/oauth/api/domain/OAuthProvider.java
>          } catch (Exception e) {
아래 if 문관련 피드백에 댓글이 안달리네요 ㅠㅠㅠ..

해당 부분 저번에 같이 고친 것으로 기억합니다. 그런데 충돌과정에서 예전 코드로 되돌아간 것 같네요 수정 해놓겠습니다 😃

2021-08-30 14:10 UTC, Sehwan-Jang approved these changes

2021-08-30 14:12 UTC, merged