[BE] 댓글 api 리팩토링
woowacourse-teams/2021-darass pull request #73
Opened 2021-07-13 07:13 UTC by Sehwan-Jang

+ 댓글 api 에 로그인 및 (수정 및 삭제하려는 경우) 유저 정보 검증 기능 추가 
+ 댓글 인수테스트 작성 
+ rest docs 반영

2021-07-13 09:43 UTC, jaeseongDev requested changes
안녕하세요 아론! 이번에 리뷰를 맡게된 제리입니다🐭

2021-07-13 09:43 UTC, jaeseongDev commented on backend/src/main/java/com/darass/darass/comment/controller/dto/CommentDeleteRequest.java
> +//@Setter
불필요한 주석은 지우는 게 어떨까요~?

2021-07-13 09:43 UTC, jaeseongDev commented on backend/src/main/java/com/darass/darass/comment/service/CommentService.java
> -        //TODO : 로그인 유저 저장 기능
로그인 유저 저장 기능이 끝났다면 주석을 지워도 좋을 것 같애요!

2021-07-13 09:43 UTC, jaeseongDev commented on backend/src/main/java/com/darass/darass/comment/service/CommentService.java
> +    private Comment modifiableComment(Long id, User user) {
메서드명을 동사 형태(~~하다)로 바꾸는 건 어떨까요~?

2021-07-13 09:43 UTC, jaeseongDev commented on backend/src/main/java/com/darass/darass/comment/service/CommentService.java
> +        Comment comment = modifiableComment(id, user);
`modifiableComment(id, user);`의 코드가 중복되는데, 코드의 중복을 없애보는 건 어떨까요 ?

2021-07-13 13:45 UTC, Sehwan-Jang commented on backend/src/main/java/com/darass/darass/comment/service/CommentService.java
> +    private Comment modifiableComment(Long id, User user) {
검증의 기능과 검증된 코멘트 객체를 반환하는 기능을 둘다 겸하고 있어
`returnValidatedComment` 로 바꿔봤습니다.
혹시  더 좋은 의견 있다면 알려주세요  ~

2021-07-13 17:03 UTC, jujubebat reviewed
전반적으로 아주 잘 작성해주셨습니다 고생많았어요 ㅎㅎ  😃

2021-07-13 17:03 UTC, jujubebat commented on backend/src/test/java/com/darass/darass/project/acceptance/ProjectAcceptanceTest.java
>      @DisplayName("/api/v1/projects POST - 성공")
위와 같은 디스플레이 네임으로는 어떤 테스트인지 쉽게 파악할 수 없다고 생각합니다!  인수테스트인 만큼 디스플레이 네임에 유저 시나리오가 드러났으면 좋겠어요. 인수테스트는 나중에 테스트코드를 전부 돌린후 디스플레이 네임만 보고 어떤 유저 시나리오인지 파악할 수 있게 해야한다고 생각합니다!!!  전반적으로 수정해줬으면 좋겠습니다. 아론 생각은 어떠신가요??

2021-07-13 17:03 UTC, jujubebat commented on backend/src/main/java/com/darass/darass/project/service/ProjectService.java
> +                .name(projectRequest.getName())
깔끔한 포메팅 정리 👍

2021-07-14 01:26 UTC, jujubebat approved these changes

2021-07-14 02:10 UTC, merged